import web3 from "./web3"

// rinkeby
const address = '0x87d503DA875B39B835a9128BE5e3920E5f07bdF9'

const mustachioAssetsAbi = [
    {
        "inputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"constructor"
    },
    {
        "anonymous":false,
        "inputs":[
            {
                "indexed":true,
                "internalType":"address",
                "name":"account",
                "type":"address"
            },
            {
                "indexed":true,
                "internalType":"address",
                "name":"operator",
                "type":"address"
            },
            {
                "indexed":false,
                "internalType":"bool",
                "name":"approved",
                "type":"bool"
            }
        ],
        "name":"ApprovalForAll",
        "type":"event"
    },
    {
        "anonymous":false,
        "inputs":[
            {
                "indexed":true,
                "internalType":"address",
                "name":"previousOwner",
                "type":"address"
            },
            {
                "indexed":true,
                "internalType":"address",
                "name":"newOwner",
                "type":"address"
            }
        ],
        "name":"OwnershipTransferred",
        "type":"event"
    },
    {
        "anonymous":false,
        "inputs":[
            {
                "indexed":true,
                "internalType":"address",
                "name":"operator",
                "type":"address"
            },
            {
                "indexed":true,
                "internalType":"address",
                "name":"from",
                "type":"address"
            },
            {
                "indexed":true,
                "internalType":"address",
                "name":"to",
                "type":"address"
            },
            {
                "indexed":false,
                "internalType":"uint256[]",
                "name":"ids",
                "type":"uint256[]"
            },
            {
                "indexed":false,
                "internalType":"uint256[]",
                "name":"values",
                "type":"uint256[]"
            }
        ],
        "name":"TransferBatch",
        "type":"event"
    },
    {
        "anonymous":false,
        "inputs":[
            {
                "indexed":true,
                "internalType":"address",
                "name":"operator",
                "type":"address"
            },
            {
                "indexed":true,
                "internalType":"address",
                "name":"from",
                "type":"address"
            },
            {
                "indexed":true,
                "internalType":"address",
                "name":"to",
                "type":"address"
            },
            {
                "indexed":false,
                "internalType":"uint256",
                "name":"id",
                "type":"uint256"
            },
            {
                "indexed":false,
                "internalType":"uint256",
                "name":"value",
                "type":"uint256"
            }
        ],
        "name":"TransferSingle",
        "type":"event"
    },
    {
        "anonymous":false,
        "inputs":[
            {
                "indexed":false,
                "internalType":"string",
                "name":"value",
                "type":"string"
            },
            {
                "indexed":true,
                "internalType":"uint256",
                "name":"id",
                "type":"uint256"
            }
        ],
        "name":"URI",
        "type":"event"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"account",
                "type":"address"
            },
            {
                "internalType":"uint256",
                "name":"id",
                "type":"uint256"
            }
        ],
        "name":"balanceOf",
        "outputs":[
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address[]",
                "name":"accounts",
                "type":"address[]"
            },
            {
                "internalType":"uint256[]",
                "name":"ids",
                "type":"uint256[]"
            }
        ],
        "name":"balanceOfBatch",
        "outputs":[
            {
                "internalType":"uint256[]",
                "name":"",
                "type":"uint256[]"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_groupId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_tokenId",
                "type":"uint256"
            }
        ],
        "name":"checkTokenIdIfInRange",
        "outputs":[
            {
                "internalType":"bool",
                "name":"",
                "type":"bool"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_groupId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_fromId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_to",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_price",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_edition",
                "type":"uint256"
            }
        ],
        "name":"createNewGroup",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_groupId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_tokenId",
                "type":"uint256"
            }
        ],
        "name":"getCurrentTokenEdition",
        "outputs":[
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_groupId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_tokenId",
                "type":"uint256"
            }
        ],
        "name":"getGroupEdition",
        "outputs":[
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_groupId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_tokenId",
                "type":"uint256"
            }
        ],
        "name":"getGroupPrice",
        "outputs":[
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_groupId",
                "type":"uint256"
            }
        ],
        "name":"getGroupRange",
        "outputs":[
            {
                "internalType":"string",
                "name":"",
                "type":"string"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"account",
                "type":"address"
            },
            {
                "internalType":"address",
                "name":"operator",
                "type":"address"
            }
        ],
        "name":"isApprovedForAll",
        "outputs":[
            {
                "internalType":"bool",
                "name":"",
                "type":"bool"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_groupId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_tokenId",
                "type":"uint256"
            }
        ],
        "name":"mintAsset",
        "outputs":[
            
        ],
        "stateMutability":"payable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"_address",
                "type":"address"
            },
            {
                "internalType":"uint256",
                "name":"_groupId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_tokenId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_quantity",
                "type":"uint256"
            }
        ],
        "name":"mintAssetRewards",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            }
        ],
        "name":"mintTokenDetails",
        "outputs":[
            {
                "internalType":"uint256",
                "name":"fromId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"to",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"price",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"edition",
                "type":"uint256"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            }
        ],
        "name":"mintedPerToken",
        "outputs":[
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            
        ],
        "name":"name",
        "outputs":[
            {
                "internalType":"string",
                "name":"",
                "type":"string"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            
        ],
        "name":"owner",
        "outputs":[
            {
                "internalType":"address",
                "name":"",
                "type":"address"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            
        ],
        "name":"renounceOwnership",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"from",
                "type":"address"
            },
            {
                "internalType":"address",
                "name":"to",
                "type":"address"
            },
            {
                "internalType":"uint256[]",
                "name":"ids",
                "type":"uint256[]"
            },
            {
                "internalType":"uint256[]",
                "name":"amounts",
                "type":"uint256[]"
            },
            {
                "internalType":"bytes",
                "name":"data",
                "type":"bytes"
            }
        ],
        "name":"safeBatchTransferFrom",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"from",
                "type":"address"
            },
            {
                "internalType":"address",
                "name":"to",
                "type":"address"
            },
            {
                "internalType":"uint256",
                "name":"id",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"amount",
                "type":"uint256"
            },
            {
                "internalType":"bytes",
                "name":"data",
                "type":"bytes"
            }
        ],
        "name":"safeTransferFrom",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"operator",
                "type":"address"
            },
            {
                "internalType":"bool",
                "name":"approved",
                "type":"bool"
            }
        ],
        "name":"setApprovalForAll",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_groupId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_price",
                "type":"uint256"
            }
        ],
        "name":"setGroupMintPrice",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_groupId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_edition",
                "type":"uint256"
            }
        ],
        "name":"setGroupTokenEdition",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_groupId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_fromId",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"_to",
                "type":"uint256"
            }
        ],
        "name":"setGroupTokenRange",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"string",
                "name":"_newUri",
                "type":"string"
            }
        ],
        "name":"setURI",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"bytes4",
                "name":"interfaceId",
                "type":"bytes4"
            }
        ],
        "name":"supportsInterface",
        "outputs":[
            {
                "internalType":"bool",
                "name":"",
                "type":"bool"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            
        ],
        "name":"symbol",
        "outputs":[
            {
                "internalType":"string",
                "name":"",
                "type":"string"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_tokenId",
                "type":"uint256"
            }
        ],
        "name":"tokenURI",
        "outputs":[
            {
                "internalType":"string",
                "name":"",
                "type":"string"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"newOwner",
                "type":"address"
            }
        ],
        "name":"transferOwnership",
        "outputs":[
            
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            }
        ],
        "name":"uri",
        "outputs":[
            {
                "internalType":"string",
                "name":"",
                "type":"string"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    }
]

export default new web3.eth.Contract(mustachioAssetsAbi, address);